import 'package:pdf/widgets.dart' as pw;

class ConstantVar {
  static List<pw.Lorem> listContent = [
    pw.Lorem(length: 5),
    pw.Lorem(length: 20),
    pw.Lorem(length: 5),
    pw.Lorem(length: 20),
    pw.Lorem(length: 5),
    pw.Lorem(length: 20),
    pw.Lorem(length: 5),
    pw.Lorem(length: 20),
    pw.Lorem(length: 5),
    pw.Lorem(length: 20),
    pw.Lorem(length: 5),
    pw.Lorem(length: 20),
    pw.Lorem(length: 5),
    pw.Lorem(length: 20),
    pw.Lorem(length: 5),
    pw.Lorem(length: 20),
    pw.Lorem(length: 5),
    pw.Lorem(length: 20),
    pw.Lorem(length: 5),
    pw.Lorem(length: 20),
    pw.Lorem(length: 5),
    pw.Lorem(length: 20),
    pw.Lorem(length: 5),
    pw.Lorem(length: 20),
    pw.Lorem(length: 5),
    pw.Lorem(length: 20),
    pw.Lorem(length: 5),
    pw.Lorem(length: 20),
    pw.Lorem(length: 5),
    pw.Lorem(length: 20),
    pw.Lorem(length: 5),
    pw.Lorem(length: 20),
    pw.Lorem(length: 5),
    pw.Lorem(length: 20),
    pw.Lorem(length: 5),
    pw.Lorem(length: 20),
    pw.Lorem(length: 5),
    pw.Lorem(length: 20),
    pw.Lorem(length: 5),
    pw.Lorem(length: 20),
    pw.Lorem(length: 5),
    pw.Lorem(length: 20),
    pw.Lorem(length: 5),
    pw.Lorem(length: 20),
    pw.Lorem(length: 5),
    pw.Lorem(length: 20),
    pw.Lorem(length: 5),
    pw.Lorem(length: 20),
    pw.Lorem(length: 5),
    pw.Lorem(length: 20),
    pw.Lorem(length: 5),
    pw.Lorem(length: 20),
    pw.Lorem(length: 5),
    pw.Lorem(length: 20),
    pw.Lorem(length: 5),
    pw.Lorem(length: 20),
    pw.Lorem(length: 5),
    pw.Lorem(length: 20),
    pw.Lorem(length: 5),
    pw.Lorem(length: 20),
  ];
}
